# -*- coding: utf-8 -*-
"""Add help_tr (everyday Turkish) to every option in options_catalog.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "app" / "options_catalog.json"

# Clear everyday Turkish help texts keyed by option id.
HELP_TR: dict[str, str] = {
    "help": "Bu yardım metnini yazdırır ve çıkar",
    "version": "Program sürümünü yazdırır ve çıkar",
    "update": "Programı en son kararlı sürüme günceller",
    "no_update": "Güncelleme denetimi yapmaz (varsayılan)",
    "update_to": "Belirli bir sürüme yükseltir/düşürür. CHANNEL bir depo da olabilir. CHANNEL ve TAG verilmezse sırasıyla \"stable\" ve \"latest\" kullanılır. Desteklenen kanallar: stable, nightly, master",
    "ignore_errors": "İndirme ve son işleme hatalarını yok sayar. Son işleme başarısız olsa bile indirme başarılı sayılır",
    "no_abort_on_error": "İndirme hatasında sonraki videoya devam eder; örneğin oynatma listesindeki eksik videoları atlamak için (varsayılan)",
    "abort_on_error": "Hata olursa sonraki videoların indirilmesini durdurur (--no-ignore-errors takma adı)",
    "list_extractors": "Desteklenen tüm çıkarıcıları listeler ve çıkar",
    "extractor_descriptions": "Desteklenen tüm çıkarıcıların açıklamalarını yazar ve çıkar",
    "use_extractors": "Kullanılacak çıkarıcı adları (virgülle). Regex, \"all\", \"default\" ve \"end\" de kullanılabilir. Adın başına \"-\" koyarak hariç tutabilirsiniz. (Takma ad: --ies)",
    "default_search": "Tam olmayan URL'ler için önek. Örn. \"gvsearch2:python\". \"auto\" tahmin ettirir; \"error\" hata verir. Varsayılan \"fixup_error\" bozuk URL'leri onarmaya çalışır",
    "ignore_config": "--config-locations ile verilenler dışında başka yapılandırma dosyası yüklemez. (Takma ad: --no-config)",
    "no_config_locations": "Özel yapılandırma dosyası yüklemez (varsayılan). Yapılandırma dosyası içinde kullanılırsa önceki --config-locations yok sayılır",
    "config_locations": "Ana yapılandırma dosyasının yolu veya içeren klasör (\"-\" = stdin). Birden çok kez kullanılabilir",
    "plugin_dirs": "Eklenti aranacak ek klasör. Birden çok kez eklenebilir. \"default\" varsayılan eklenti klasörlerini arar",
    "no_plugin_dirs": "Varsayılanlar ve önceki --plugin-dirs dahil eklenti arama klasörlerini temizler",
    "js_runtimes": "Ek JavaScript çalışma zamanı (isteğe bağlı yol ile). Öncelik: deno, node, quickjs, bun. Varsayılan yalnızca \"deno\". Birden çok kez kullanılabilir",
    "no_js_runtimes": "Varsayılanlar ve önceki --js-runtimes dahil JS çalışma zamanlarını temizler",
    "remote_components": "Gerektiğinde indirilmesine izin verilen uzak bileşenler (ör. ejs:npm, ejs:github). Varsayılan olarak uzak bileşene izin yok",
    "no_remote_components": "Tüm uzak bileşen indirmelerini yasaklar",
    "flat_playlist": "Oynatma listesi girdilerinin URL sonuçlarını çıkarmaz; bazı meta veriler eksik olabilir",
    "no_flat_playlist": "Oynatma listesindeki videoları tam olarak çıkarır (varsayılan)",
    "live_from_start": "Canlı yayınları başından indirir (deneysel; YouTube, Twitch, TVer, mellow-fan)",
    "no_live_from_start": "Canlı yayınları geçerli andan itibaren indirir (varsayılan)",
    "wait_for_video": "Zamanlanmış yayınların hazır olmasını bekler. Denemeler arası minimum saniye (veya aralık)",
    "no_wait_for_video": "Zamanlanmış yayınları beklemez (varsayılan)",
    "mark_watched": "Videoları izlenmiş işaretler (--simulate ile bile)",
    "no_mark_watched": "Videoları izlenmiş işaretlemez (varsayılan)",
    "color": "Çıktıda renk kodları kullanılsın mı: always, auto (varsayılan), never veya no_color. İsteğe bağlı STREAM öneki (stdout/stderr). Birden çok kez kullanılabilir",
    "compat_options": "youtube-dl / youtube-dlc uyumluluğu için yt-dlp değişikliklerini geri alan seçenekler",
    "alias": "Bir seçenek dizisi için takma ad oluşturur. Örn. --alias get-audio \"-x --audio-format {0}\". En fazla 100 tetikleme güvenliği vardır. Birden çok kez kullanılabilir",
    "preset_alias": "Hazır seçenek seti uygular (mp3, aac, mp4, mkv, sleep). Birden çok kez kullanılabilir",
    "proxy": "HTTP/HTTPS/SOCKS vekil sunucusu. SOCKS için örn. socks5://kullanici:sifre@127.0.0.1:1080/. Doğrudan bağlantı için boş dize",
    "socket_timeout": "Vazgeçmeden önce beklenecek süre (saniye)",
    "source_address": "Bağlanılacak istemci tarafı IP adresi",
    "impersonate": "İsteklerde taklit edilecek istemci (chrome, chrome-110 vb.). Boş dize herhangi bir istemciyi taklit eder",
    "list_impersonate_targets": "Taklit edilebilecek istemcileri listeler",
    "force_ipv4": "Tüm bağlantıları IPv4 üzerinden yapar",
    "force_ipv6": "Tüm bağlantıları IPv6 üzerinden yapar",
    "enable_file_urls": "file:// URL'lerini etkinleştirir (güvenlik nedeniyle varsayılan kapalı)",
    "geo_verification_proxy": "Coğrafi kısıtlı sitelerde IP doğrulaması için vekil. Asıl indirme --proxy ile yapılır",
    "xff": "Coğrafi kısıtlamayı aşmak için X-Forwarded-For sahteciliği: default, never, CIDR IP bloğu veya ISO ülke kodu",
    "playlist_items": "İndirilecek oynatma listesi indeksleri (virgülle). Aralık: [START]:[STOP][:STEP]. Negatif indeks sondan sayar",
    "min_filesize": "Dosya boyutu SIZE'dan küçükse indirmeyi iptal eder (örn. 50k, 44.6M)",
    "max_filesize": "Dosya boyutu SIZE'dan büyükse indirmeyi iptal eder (örn. 50k, 44.6M)",
    "date": "Yalnızca bu tarihte yüklenen videoları indirir (YYYYMMDD veya today-2weeks gibi)",
    "datebefore": "Bu tarihte veya öncesinde yüklenen videoları indirir (--date ile aynı biçimler)",
    "dateafter": "Bu tarihte veya sonrasında yüklenen videoları indirir (--date ile aynı biçimler)",
    "match_filters": "Genel video süzgeci. Alan karşılaştırması, !alan, & ile birleşik koşullar. Birden çok kez OR gibi davranır. \"-\" ile etkileşimli sorar",
    "no_match_filters": "--match-filters kullanmaz (varsayılan)",
    "break_match_filters": "--match-filters gibi ama video reddedilince indirmeyi durdurur",
    "no_break_match_filters": "--break-match-filters kullanmaz (varsayılan)",
    "no_playlist": "URL hem video hem listedeyse yalnızca videoyu indirir",
    "yes_playlist": "URL hem video hem listedeyse oynatma listesini indirir",
    "age_limit": "Yalnızca verilen yaşa uygun videoları indirir",
    "download_archive": "Arşiv dosyasında olmayan videoları indirir; indirilen kimlikleri kaydeder",
    "no_download_archive": "Arşiv dosyası kullanmaz (varsayılan)",
    "max_downloads": "NUMBER dosya indirdikten sonra durur",
    "break_on_existing": "Arşivde bulunan bir dosyayla karşılaşınca indirmeyi durdurur",
    "no_break_on_existing": "Arşivde bulunan dosyada durmaz (varsayılan)",
    "break_per_input": "--max-downloads, --break-on-existing vb. sayaçlarını her giriş URL'sinde sıfırlar",
    "no_break_per_input": "--break-on-existing benzeri seçenekler tüm indirme kuyruğunu sonlandırır",
    "skip_playlist_after_errors": "Bu kadar hatadan sonra oynatma listesinin geri kalanı atlanır",
    "concurrent_fragments": "DASH/HLS parçalarının eşzamanlı indirme sayısı (varsayılan 1)",
    "limit_rate": "En yüksek indirme hızı (bayt/sn), örn. 50K veya 4.2M",
    "throttled_rate": "Bu hızın altına düşünce kısıtlama varsayılır ve veri yeniden çıkarılır (örn. 100K)",
    "retries": "Yeniden deneme sayısı (varsayılan 10) veya \"infinite\"",
    "file_access_retries": "Dosya erişim hatasında deneme sayısı (varsayılan 3) veya \"infinite\"",
    "fragment_retries": "Parça için deneme sayısı (varsayılan 10) veya \"infinite\"",
    "retry_sleep": "Denemeler arası bekleme (sn); isteğe bağlı http/fragment/file_access/extractor öneki. linear= veya exp= ifadeleri desteklenir",
    "skip_unavailable_fragments": "DASH/HLS/ISM'de eksik parçaları atlar (varsayılan)",
    "abort_on_unavailable_fragments": "Bir parça yoksa indirmeyi iptal eder",
    "keep_fragments": "İndirme bitince parçaları diskte tutar",
    "no_keep_fragments": "İndirme bitince parçaları siler (varsayılan)",
    "buffer_size": "İndirme tampon boyutu, örn. 1024 veya 16K (varsayılan 1024)",
    "resize_buffer": "Tampon boyutunu --buffer-size'dan başlayarak otomatik ayarlar (varsayılan)",
    "no_resize_buffer": "Tampon boyutunu otomatik ayarlamaz",
    "http_chunk_size": "Parçalı HTTP indirme boyutu, örn. 10M (varsayılan kapalı; deneysel)",
    "playlist_random": "Oynatma listesini rastgele sırada indirir",
    "lazy_playlist": "Liste girdilerini geldikçe işler; n_entries, --playlist-random ve --playlist-reverse'i kapatır",
    "no_lazy_playlist": "Tüm liste ayrıştırıldıktan sonra işler (varsayılan)",
    "hls_use_mpegts": "HLS için mpegts kabı kullanır; indirme sırasında oynatma ve kesintiye karşı daha dayanıklı (canlıda varsayılan)",
    "no_hls_use_mpegts": "HLS için mpegts kullanmaz (canlı olmayan indirmede varsayılan)",
    "download_sections": "Düzenli ifadeyle eşleşen bölümleri indirir. \"*\" öneki zaman aralığıdır. ffmpeg gerekir. Birden çok kez kullanılabilir",
    "downloader": "Harici indirici adı/yolu (isteğe bağlı protokol öneki). native, aria2c, axel, curl, ffmpeg, httpie, wget. Birden çok kez kullanılabilir",
    "downloader_args": "Harici indiriciye argümanlar: indirici:argümanlar. Birden çok kez kullanılabilir",
    "batch_file": "İndirilecek URL'leri içeren dosya (satır başına bir; \"-\" = stdin). # ; ] ile başlayanlar yorum",
    "no_batch_file": "Toplu URL dosyası okumaz (varsayılan)",
    "paths": "Dosya türü:yol ile indirme yolları. home ve temp desteklenir. Mutlak --output varsa yok sayılır",
    "output": "Çıktı dosya adı şablonu (OUTPUT TEMPLATE)",
    "output_na_placeholder": "--output'ta eksik alanlar için yer tutucu (varsayılan: NA)",
    "restrict_filenames": "Dosya adlarını yalnızca ASCII yapar; & ve boşluktan kaçınır",
    "no_restrict_filenames": "Unicode, & ve boşluğa izin verir (varsayılan)",
    "windows_filenames": "Dosya adlarını Windows uyumlu zorunlu kılar",
    "no_windows_filenames": "Dosya adlarını yalnızca minimal temizler",
    "trim_filenames": "Uzantı hariç dosya adı uzunluğunu karakter sayısıyla sınırlar",
    "no_overwrites": "Hiçbir dosyanın üzerine yazmaz",
    "force_overwrites": "Tüm video ve meta dosyaların üzerine yazar (--no-continue dahil)",
    "no_force_overwrites": "Videonun üzerine yazmaz ama ilgili dosyaların üzerine yazar (varsayılan)",
    "continue": "Kısmen indirilmiş dosya/parçalara devam eder (varsayılan)",
    "no_continue": "Kısmi parçalara devam etmez; parçalı değilse baştan indirir",
    "part": "Doğrudan yazmak yerine .part dosyası kullanır (varsayılan)",
    "no_part": ".part kullanmaz; doğrudan çıktı dosyasına yazar",
    "mtime": "Last-modified başlığıyla dosya değiştirme zamanını ayarlar",
    "no_mtime": "Last-modified ile zaman ayarlamaz (varsayılan)",
    "write_description": "Video açıklamasını .description dosyasına yazar",
    "no_write_description": "Video açıklaması yazmaz (varsayılan)",
    "write_info_json": "Video meta verisini .info.json dosyasına yazar (kişisel bilgi içerebilir)",
    "no_write_info_json": "Video meta verisi yazmaz (varsayılan)",
    "write_playlist_metafiles": "--write-info-json vb. ile oynatma listesi meta verisini de yazar (varsayılan)",
    "no_write_playlist_metafiles": "Oynatma listesi meta verisini yazmaz",
    "clean_info_json": "infojson'dan dosya adı gibi iç meta verileri çıkarır (varsayılan)",
    "no_clean_info_json": "infojson'a tüm alanları yazar",
    "write_comments": "Video yorumlarını infojson'a almak için çeker (Takma ad: --get-comments)",
    "no_write_comments": "Hızlı olmadığı sürece yorum çekmez (Takma ad: --no-get-comments)",
    "load_info_json": "Video bilgisini içeren JSON dosyası (--write-info-json ile oluşturulmuş)",
    "cookies": "Netscape biçimli çerez dosyası (okuma ve yazma)",
    "no_cookies": "Çerez dosyası okumaz/yazmaz (varsayılan)",
    "cookies_from_browser": "Çerezlerin alınacağı tarayıcı (brave, chrome, edge, firefox vb.). İsteğe bağlı profil/anahtarlık/kapsayıcı",
    "no_cookies_from_browser": "Tarayıcıdan çerez yüklemez (varsayılan)",
    "cache_dir": "yt-dlp'nin kalıcı önbellek klasörü (varsayılan: ${XDG_CACHE_HOME}/yt-dlp)",
    "no_cache_dir": "Dosya sistemi önbelleğini kapatır",
    "rm_cache_dir": "Tüm dosya sistemi önbellek dosyalarını siler",
    "write_thumbnail": "Küçük resmi diske yazar",
    "no_write_thumbnail": "Küçük resmi yazmaz (varsayılan)",
    "write_all_thumbnails": "Tüm küçük resim biçimlerini diske yazar",
    "list_thumbnails": "Her videonun kullanılabilir küçük resimlerini listeler (simülasyon)",
    "write_link": "Platforma göre internet kısayolu yazar (.url / .webloc / .desktop)",
    "write_url_link": "Windows .url internet kısayolu yazar",
    "write_webloc_link": "macOS .webloc internet kısayolu yazar",
    "write_desktop_link": "Linux .desktop internet kısayolu yazar",
    "quiet": "Sessiz kip. --verbose ile birlikte log stderr'e gider",
    "no_quiet": "Sessiz kipi kapatır (varsayılan)",
    "no_warnings": "Uyarıları yok sayar",
    "simulate": "Videoyu indirmez ve diske bir şey yazmaz",
    "no_simulate": "Listeleme seçenekleri olsa bile videoyu indirir",
    "ignore_no_formats_error": "\"Biçim yok\" hatasını yok sayar; meta veri çıkarmak için yararlı (deneysel)",
    "no_ignore_no_formats_error": "İndirilebilir biçim yoksa hata verir (varsayılan)",
    "skip_download": "Videoyu indirmez ama ilgili dosyaları yazar (Takma ad: --no-download)",
    "print": "Ekrana yazılacak alan veya şablon; isteğe bağlı WHEN: öneki. --quiet ima eder. Birden çok kez kullanılabilir",
    "print_to_file": "Verilen şablonu dosyaya ekler. WHEN ve TEMPLATE --print ile aynı. Birden çok kez kullanılabilir",
    "dump_json": "Her video için JSON yazar (sessiz). Simülasyon yapar (--no-simulate yoksa)",
    "dump_single_json": "Her URL/infojson için JSON yazar. Oynatma listesinde tüm bilgi tek satırda",
    "force_write_archive": "Simülasyon olsa bile hata yoksa arşiv girdilerini yazar",
    "newline": "İlerleme çubuğunu satır satır yazar",
    "no_progress": "İlerleme çubuğu yazdırmaz",
    "progress": "Sessiz kipte bile ilerleme çubuğu gösterir",
    "console_title": "İlerlemeyi konsol başlığında gösterir",
    "progress_template": "İlerleme çıktısı şablonu; download:, download-title:, postprocess: önekleri. info ve progress anahtarları",
    "progress_delta": "İlerleme çıktıları arasındaki süre (varsayılan: 0)",
    "verbose": "Çeşitli hata ayıklama bilgilerini yazdırır",
    "dump_pages": "İndirilen sayfaları base64 ile yazdırır (çok ayrıntılı)",
    "write_pages": "Ara sayfaları geçerli klasöre dosya olarak yazar",
    "print_traffic": "Gönderilen ve okunan HTTP trafiğini gösterir",
    "encoding": "Belirtilen kodlamayı zorlar (deneysel)",
    "legacy_server_connect": "RFC 5746 güvenli yeniden anlaşmayı desteklemeyen HTTPS sunucularına izin verir",
    "no_check_certificates": "HTTPS sertifika doğrulamasını kapatır",
    "prefer_insecure": "Video bilgisi için şifresiz bağlantı kullanır",
    "add_headers": "Özel HTTP başlığı:değer ekler. Birden çok kez kullanılabilir",
    "bidi_workaround": "Çift yönlü metin desteği zayıf terminaller için çözüm (bidiv/fribidi gerekir)",
    "sleep_requests": "Veri çıkarımı sırasında istekler arası bekleme (saniye)",
    "sleep_interval": "Her indirmeden önce bekleme (sn). --max-sleep-interval ile birlikte minimumdur",
    "max_sleep_interval": "En fazla bekleme süresi (sn). Yalnızca --min-sleep-interval ile",
    "sleep_subtitles": "Her altyazı indirmeden önce bekleme (saniye)",
    "format": "Video biçim kodu (FORMAT SELECTION)",
    "format_sort": "Biçimleri verilen alanlara göre sıralar (Sorting Formats)",
    "format_sort_reset": "Önceki kullanıcı sıralamasını yok sayıp varsayılana döner",
    "format_sort_force": "Kullanıcı sıralamasını tüm alanlara üstün kılar (Takma ad: --S-force)",
    "no_format_sort_force": "Bazı alanlar kullanıcı sıralamasından önce gelir (varsayılan)",
    "video_multistreams": "Birden çok video akışının tek dosyada birleştirilmesine izin verir",
    "no_video_multistreams": "Her çıktı için yalnızca bir video akışı indirir (varsayılan)",
    "audio_multistreams": "Birden çok ses akışının tek dosyada birleştirilmesine izin verir",
    "no_audio_multistreams": "Her çıktı için yalnızca bir ses akışı indirir (varsayılan)",
    "prefer_free_formats": "Aynı kalitede ücretsiz kapları tercih eder. \"-S ext\" ile kaliteden bağımsız sıkı tercih",
    "no_prefer_free_formats": "Ücretsiz kaplara özel tercih vermez (varsayılan)",
    "check_formats": "Yalnızca gerçekten indirilebilir biçimleri seçer",
    "check_all_formats": "Tüm biçimlerin indirilebilirliğini denetler",
    "no_check_formats": "Biçimlerin indirilebilirliğini denetlemez",
    "list_formats": "Her videonun biçimlerini listeler (simülasyon)",
    "merge_output_format": "Birleştirmede kullanılabilecek kaplar, \"/\" ile ayrılır (örn. mp4/mkv)",
    "write_subs": "Altyazı dosyası yazar",
    "no_write_subs": "Altyazı dosyası yazmaz (varsayılan)",
    "write_auto_subs": "Otomatik oluşturulmuş altyazı yazar (Takma ad: --write-automatic-subs)",
    "no_write_auto_subs": "Otomatik altyazı yazmaz (varsayılan)",
    "list_subs": "Her videonun altyazılarını listeler (simülasyon)",
    "sub_format": "Altyazı biçimi; \"/\" ile tercih sırası (örn. srt veya ass/srt/best)",
    "sub_langs": "İndirilecek altyazı dilleri (regex veya all), virgülle. \"-\" önekiyle hariç tutma. --list-subs ile etiketleri görün",
    "username": "Bu hesap kimliğiyle oturum açar",
    "password": "Hesap parolası. Verilmezse etkileşimli sorulur",
    "twofactor": "İki adımlı doğrulama kodu",
    "netrc": ".netrc kimlik doğrulama verisini kullanır",
    "netrc_location": ".netrc konumu (dosya veya klasör). Varsayılan ~/.netrc",
    "netrc_cmd": "Çıkarıcı için kimlik bilgisi almak üzere çalıştırılacak komut",
    "video_password": "Videoya özel parola",
    "ap_mso": "Adobe Pass TV sağlayıcı (MSO) kimliği; --ap-list-mso ile liste",
    "ap_username": "MSO hesap kullanıcı adı",
    "ap_password": "MSO hesap parolası. Verilmezse etkileşimli sorulur",
    "ap_list_mso": "Desteklenen tüm MSO'ları listeler",
    "client_certificate": "PEM biçimli istemci sertifikası yolu (özel anahtar dahil olabilir)",
    "client_certificate_key": "İstemci sertifikası özel anahtar dosyası yolu",
    "client_certificate_password": "Şifreli özel anahtar parolası. Yoksa etkileşimli sorulur",
    "extract_audio": "Video dosyalarını yalnızca sese dönüştürür (ffmpeg ve ffprobe gerekir)",
    "audio_format": "-x ile ses dönüşüm biçimi: best (varsayılan), aac, alac, flac, m4a, mp3, opus, vorbis, wav",
    "audio_quality": "-x ile ffmpeg ses kalitesi: 0 (en iyi)–10 (en kötü) VBR veya 128K gibi bit hızı (varsayılan 5)",
    "remux_video": "Gerekirse videoyu başka kaba yeniden mux'lar (mp4, mkv, webm vb.). Birden çok kural: aac>m4a/mov>mp4/mkv",
    "recode_video": "Gerekirse videoyu yeniden kodlar (--remux-video ile aynı sözdizimi)",
    "postprocessor_args": "Son işleyicilere argüman: ad:argümanlar. Merger, ExtractAudio, Metadata vb. (Takma ad: --ppa)",
    "keep_video": "Son işlemeden sonra ara video dosyasını diskte tutar",
    "no_keep_video": "Son işlemeden sonra ara videoyu siler (varsayılan)",
    "post_overwrites": "Son işlenmiş dosyaların üzerine yazar (varsayılan)",
    "no_post_overwrites": "Son işlenmiş dosyaların üzerine yazmaz",
    "embed_subs": "Altyazıları videoya gömer (mp4, webm, mkv)",
    "no_embed_subs": "Altyazı gömmez (varsayılan)",
    "embed_thumbnail": "Küçük resmi kapak olarak videoya gömer",
    "no_embed_thumbnail": "Küçük resim gömmez (varsayılan)",
    "embed_metadata": "Meta veriyi videoya gömer; bölüm/infojson de (Takma ad: --add-metadata)",
    "no_embed_metadata": "Dosyaya meta veri eklemez (varsayılan)",
    "embed_chapters": "Videoya bölüm işaretleri ekler (Takma ad: --add-chapters)",
    "no_embed_chapters": "Bölüm işareti eklemez (varsayılan)",
    "embed_info_json": "infojson'u mkv/mka dosyasına ek olarak gömer",
    "no_embed_info_json": "infojson ekini gömmez",
    "parse_metadata": "Başka alanlardan başlık/sanatçı gibi ek meta veri ayrıştırır (MODIFYING METADATA)",
    "replace_in_metadata": "Meta veri alanında regex ile metin değiştirir. Birden çok kez kullanılabilir",
    "xattrs": "Meta veriyi dosyanın xattr'larına yazar (Dublin Core / XDG)",
    "concat_playlist": "Oynatma listesi videolarını birleştirir: never, always veya multi_video (varsayılan). Aynı kodek gerekir",
    "fixup": "Bilinen dosya hatalarını düzeltir: never, warn, detect_or_warn (varsayılan), force",
    "ffmpeg_location": "ffmpeg ikilisinin yolu veya içeren klasör",
    "exec": "Komut çalıştırır; isteğe bağlı WHEN: öneki. Çıktı şablonu alanları güvenli dönüşümlerle. Birden çok kez kullanılabilir",
    "no_exec": "Önceden tanımlı --exec'leri kaldırır",
    "convert_subs": "Altyazıları başka biçime dönüştürür (ass, lrc, srt, vtt). \"none\" ile kapatılır",
    "convert_thumbnails": "Küçük resimleri başka biçime dönüştürür (jpg, png, webp). \"none\" ile kapatılır",
    "split_chapters": "İç bölümlere göre videoyu birden çok dosyaya böler. chapter: öneki çıktı adı için",
    "no_split_chapters": "Bölümlere göre bölmez (varsayılan)",
    "remove_chapters": "Başlığı regex ile eşleşen bölümleri kaldırır (--download-sections sözdizimi). Birden çok kez",
    "no_remove_chapters": "Dosyadan bölüm kaldırmaz (varsayılan)",
    "force_keyframes_at_cuts": "Kesitlerde anahtar kare zorlar (yavaş, yeniden kodlama; kesitlerde daha az bozulma)",
    "no_force_keyframes_at_cuts": "Kesmede anahtar kare zorlamaz (varsayılan)",
    "use_postprocessor": "Eklenti son işleyici adı ve isteğe bağlı argümanlar (ad:ARGS). when= ile zamanlama. Birden çok kez kullanılabilir",
    "sponsorblock_mark": "SponsorBlock kategorilerinden bölüm oluşturur (sponsor, intro, outro…). \"-\" ile hariç tutma",
    "sponsorblock_remove": "SponsorBlock kategorilerini videodan çıkarır. mark ve remove'da aynıysa remove önceliklidir",
    "sponsorblock_chapter_title": "--sponsorblock-mark ile oluşturulan bölüm başlığı şablonu. Varsayılan: [SponsorBlock]: %(category_names)l",
    "no_sponsorblock": "--sponsorblock-mark ve --sponsorblock-remove'u kapatır",
    "sponsorblock_api": "SponsorBlock API adresi (varsayılan: https://sponsor.ajay.app)",
    "extractor_retries": "Bilinen çıkarıcı hatalarında deneme sayısı (varsayılan 3) veya \"infinite\"",
    "allow_dynamic_mpd": "Dinamik DASH bildirimlerini işler (varsayılan)",
    "ignore_dynamic_mpd": "Dinamik DASH bildirimlerini işlemez",
    "hls_split_discontinuity": "HLS listelerini reklam gibi kesintilerde farklı biçimlere böler",
    "no_hls_split_discontinuity": "HLS'yi kesintilerde bölmez (varsayılan)",
    "extractor_args": "IE_KEY çıkarıcısına ARGS verir (EXTRACTOR ARGUMENTS). Birden çok kez kullanılabilir",
    "preset_mp3": "MP3 ses için hazır ayar: en iyi ses + -x --audio-format mp3",
    "preset_aac": "AAC ses için hazır ayar: uygun ses akışı + -x --audio-format aac",
    "preset_mp4": "MP4 birleştirme/remux ve H.264/AAC tercih sıralaması",
    "preset_mkv": "MKV birleştirme ve remux hazır ayarı",
    "preset_sleep": "İstek/altyazı/indirme aralarında nazik bekleme hazır ayarı",
}


def main() -> None:
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    missing: list[str] = []
    count = 0
    for section in data.get("sections", []):
        for opt in section.get("options", []):
            oid = opt["id"]
            tr = HELP_TR.get(oid)
            if not tr:
                missing.append(oid)
                # fallback: keep English marked so UI still has text
                tr = opt.get("help") or oid
            opt["help_tr"] = tr
            count += 1
    if missing:
        raise SystemExit(f"Missing translations for {len(missing)} ids: {missing}")
    CATALOG.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote help_tr for {count} options -> {CATALOG}")


if __name__ == "__main__":
    main()
